spring:
  docker:
    compose:
      enabled: true
      file: ./code/parallel_transaction_deadlock/compose.yaml
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 20000
      connection-timeout: 30000
