services:
  mysql:
    image: 'mysql:8.0.32'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
